# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Replace <track> with the track name
# Replace <image-name> with an image to run the jobs on
# Replace <action to setup tooling> with a github action to setup tooling on the image
# Replace <install dependencies> with a cli command to install the dependencies
# Replace <code-extensions> with file extensions that should trigger the workflow
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - scripts/ci-check
# - scripts/ci

name: solidity / main

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  precheck:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Use Node LTS
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          # Here, use the LTS/stable version of the track's tooling, e.g.:
          node-version: 12.4

      - name: Install project dependencies
        run: yarn

      - name: Run exercism/solidity ci pre-check (checks config, lint code) for all exercises
        run: bin/ci

  ci:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        # Here, add all SUPPORTED versions only, e.g.:
        version: [10.x, 12.x, 14.x]
        # Optionally, add more matrix variables, such as os or arch

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Use Node ${{ matrix.version }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b

      - name: Install project dependencies
        run: yarn

      - name: Run exercism/solidity ci (runs tests) for all exercises
        run: bin/ci
